[project]
name = "media"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/media/media/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.media-library-access]
path = "contracts/media-library-access.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
